keep_vars = true
name = "cf-subcloud"
main = "dist/_worker.js"
compatibility_date = "2026-07-09"
compatibility_flags = ["nodejs_compat"]
routes = [
    { pattern = "ss.zworks.me", custom_domain = true },
]
[assets]
directory = "./template"
binding = "ASSETS"

[[d1_databases]]
binding = "SHORT_LINK"
database_name = "cf-subcloud-links"
database_id = "1896b371-dca1-4bcb-93e1-c6c6be40f39e"
