keep_vars = true
name = "cf-subcloud"
main = "dist/_worker.js"
compatibility_date = "2026-07-09"
compatibility_flags = ["nodejs_compat"]
[assets]
directory = "./template"
binding = "ASSETS"

[[r2_buckets]]
binding = "SHORT_LINK"
bucket_name = "cf-subcloud-links"
